[2025-07-13T04:45:00.893+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_etl_pipeline.load_processed_covid_data manual__2025-07-13T04:44:41.676757+00:00 [queued]>
[2025-07-13T04:45:00.908+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_etl_pipeline.load_processed_covid_data manual__2025-07-13T04:44:41.676757+00:00 [queued]>
[2025-07-13T04:45:00.909+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-13T04:45:00.941+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_processed_covid_data> on 2025-07-13 04:44:41.676757+00:00
[2025-07-13T04:45:00.951+0000] {standard_task_runner.py:60} INFO - Started process 299 to run task
[2025-07-13T04:45:00.956+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'main_etl_pipeline', 'load_processed_covid_data', 'manual__2025-07-13T04:44:41.676757+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp7_syhkth']
[2025-07-13T04:45:00.961+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask load_processed_covid_data
[2025-07-13T04:45:01.053+0000] {task_command.py:423} INFO - Running <TaskInstance: main_etl_pipeline.load_processed_covid_data manual__2025-07-13T04:44:41.676757+00:00 [running]> on host 23913323947a
[2025-07-13T04:45:01.221+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_processed_covid_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-13T04:44:41.676757+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-13T04:44:41.676757+00:00'
[2025-07-13T04:45:01.249+0000] {logging_mixin.py:188} INFO - DEBUG: Contenido de processed_data recibido en load_processed_data_to_mongo: {'date': '2023-03-09T00:00:00', 'last_update_utc': '2023-03-10T04:21:03', 'total_confirmed': 7483444, 'confirmed_daily_change': 8225, 'total_deaths': 333188, 'deaths_daily_change': 52, 'total_recovered': 0, 'recovered_daily_change': 0, 'total_active': 7150256, 'active_daily_change': 8173, 'fatality_rate': 0.0445, 'country_iso': 'MEX', 'is_high_deaths_day': False, 'active_to_confirmed_ratio': 0.9554766495212632, 'recovery_rate': 0.0, 'transformation_timestamp': '2025-07-13T04:44:58.681700'}
[2025-07-13T04:45:01.250+0000] {logging_mixin.py:188} INFO - DEBUG: Tipo de processed_data: <class 'dict'>
[2025-07-13T04:45:01.252+0000] {logging_mixin.py:188} INFO - Iniciando carga de datos transformados de COVID-19...
[2025-07-13T04:45:03.192+0000] {logging_mixin.py:188} INFO - Datos transformados de COVID-19 cargados exitosamente en covid_db.processed_covid_data.
[2025-07-13T04:45:03.221+0000] {logging_mixin.py:188} INFO - Registros cargados de COVID-19 (procesados): 1
[2025-07-13T04:45:03.358+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-13T04:45:03.440+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=main_etl_pipeline, task_id=load_processed_covid_data, execution_date=20250713T044441, start_date=20250713T044500, end_date=20250713T044503
[2025-07-13T04:45:03.709+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-13T04:45:03.898+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
